### ISSUE TITLE
Admin command restrictions

### ISSUE THREAD

**Issue by vaindil** [vaindil/wazebot-discord#12]
Some regions have started to require that a Google Form be filled out to access the region's Discord server. This is a major privacy concern and is unacceptable in any online community. No user should be required to hand over their personal information to join a community except where absolutely necessary. The reasons given for Waze regions requiring an email address are severely lacking. It was even suggested at one point that phone numbers should be collected. I cannot support a system that violates user privacy like this. (As an anecdote, I would never have started editing if I were required by the editing community to provide my email address like this. Period.)

As a result, each region that requires an email address will have its admin commands restricted as long as the email address is a required form field to gain access to the region's Discord server. No basic user functionality will be affected, as my goal is not to punish anyone. This functionality will therefore be disabled:

 * Creating, updating, or removing autoreplies
 * Granting roles above L3 to users using bot commands
 * Granting region roles to users using the bot command
 * Additional config changes, such as syncing Hangouts chats to Discord (nothing already existing will be altered)

Each server and its required signup form is below. Regions that require an email address to sign up are noted as well. This issue will be kept up-to-date as I'm informed that the email address field is made optional.

 * Northwest - no form required
 * Southwest - no form required
 * Plains - no form required
 * South Central - no form required
 * Great Lakes - no form required
 * [South Atlantic](https://docs.google.com/forms/d/e/1FAIpQLScAJVxgmClRe94SOzQgRE40ggsmWHBpJ3bo1uddZVXn4aIlLg/viewform) - not required
 * Southeast - no form required
 * New England - no form required
 * Northeast - no form required
 * ~~[Mid Atlantic](https://docs.google.com/forms/d/e/1FAIpQLSc9Z1yeGdfzrzUHHUM05X7kuqxfWipgNmr8WLFfnn2m4QSgkA/viewform) - **required**~~
 * NA - no form required
 * Global - no form required

**Comment by PesachZ** [comment]
Disabling existing features in the bot as an enforcement tool on the general community instead of through discussion and community consensus in the proper channels is selfish. It means that you value your opinion above the needs and wants of the community.
The forms you mention are all entirely optional. It is, and has been for a while, possible to join any of the official Waze community servers without using any form at all by using the direct invite links which are all pinned in the #general channel of the national Waze_us server. Using the direct link to join a server completely bypasses the form, and the privacy concerns you are basing this on.
I have always supported your development and contributions, but I cannot support this action. I feel this is misguided, and an uncalled for abuse of the power the community has trusted you with based on commitments and assurances you gave.

**Comment by vaindil** [comment]
> Disabling existing features in the bot as an enforcement tool on the general community instead of through discussion and community consensus in the proper channels is selfish. It means that you value your opinion above the needs and wants of the community.

The problem with this statement is that I actually did attempt to discuss this via the proper channels. Each time I did, however, I was told that it's not my place to question these decisions. It's difficult to come to a consensus as a community when your opinion won't even be heard. Here's an example:

![image-6](https://user-images.githubusercontent.com/771134/30524905-9593d0ca-9bca-11e7-9da8-9e7831676f87.png)

Every person I discussed this with who _isn't_ in leadership has agreed with me. I'm not exaggerating when I say _every person_. The leadership seems to be the only group of people who holds the opinion that collecting email addresses is necessary. I would wager a guess that you would discover this too if you bothered to ask anyone outside that group.

> The forms you mention are all entirely optional. It is, and has been for a while, possible to join any of the official Waze community servers without using any form at all by using the direct invite links which are all pinned in the #general channel of the national Waze_us server. Using the direct link to join a server completely bypasses the form, and the privacy concerns you are basing this on.

The forms are currently optional, yes, and someone can join a server with those links, but the forms are becoming mandatory in the near future. If you didn't know this, you should have. The two servers with the form requirement are wording it like this:

![capture](https://user-images.githubusercontent.com/771134/30524947-41e2f270-9bcb-11e7-8a6a-63fd464f74cd.PNG)

This does not say "the form is optional" or "you can alternatively use this link to join the server directly". It says "if people want to join, they need to use this form". That doesn't sound very optional to me. Additionally, the only link to the MAR server from the forum is via [this post](https://www.waze.com/forum/viewtopic.php?t=237826#p1703389) (archived [here](https://user-images.githubusercontent.com/771134/30525009-6bf6df94-9bcc-11e7-8ed6-8fc1f5f306ea.PNG)). Note again that no direct link is provided, no option to bypass the form is available.

> I feel this is misguided, and an uncalled for abuse of the power the community has trusted you with

I feel that the leadership's unwillingness to listen to the community is exactly the same abuse of power. Note that I'm not doing this solely because of privacy concerns. Obviously that's the main factor here, but there are times that it makes sense to, for example, collect email addresses. Despite all of my pushing, however, I have not once received an answer as to _why_ the email addresses are being collected, other than "because we said so". If literally any reason were provided then I would be able to consider those points moving forward, but it's difficult to reason with blind authority.

**Comment by PesachZ** [comment]
Not to get into a ping debate but just to cover a few points you mentioned above.
1) you were not told it's not "your place to question these decisions", you were "this" (read: the private channel with the stated purpose of designing the architecture of the Discord servers themselves, with only a few members of leadership, and not open to the general community) is no the right place to have that discussion. You were asked several times, including in the snippet your screenshot depicts to "take the the discussion to a new venue"; namely to discuss it with the full community, in the proper channel for that community, be it the region or the whole US. Not to continue discussing it with a small working group tasked with a specific project of which this point is related, but not the task-at-hand. This is the same that I asked above, please discuss this in the *proper* location with the *community* (not just a handful working on designing server structure).

2) You claim to have never been told any reason why emails were collected, yet I know you were told they were used to grant access to regional resources such as Google Docs, Sheets, etc which are not open to the public at large, and are used as tolls of the editing community. You were also told they are used for sending invitations to events etc. You may not like the reasons, or deem them insufficient, but they were given nonetheless. Mischaracterizing the exchange is dishonest.

3) yes the post and the Forum and the form itself do not give the link to the server, but the link does exist and is accessible to anyone from the national pinned messages. Whether or not something is planned to become mandatory in the future currently it is optional so taking enforcement action before a crime so to speak is committed is wrong. The option to bypass the Forum does exist and just because it isn't mentioned doesn't change that fact that it is possible.

4) leadership is willing to listen if it's brought up in the correct Forum or venue. A problem with a Region's data collection should be addressed in that region with the leadership of that region and with the participation and input of the members of that region which has not happened as far as I know. Not once do I recall the answer being because we said so. As a group we always try to give the rationale for a decisions that are made, except in cases where we are unable to because the decision is based on proprietary and confidential information we are not authorized yet to share.

You conclude by saying that if any reasons were given at all you would consider them however reasons have been given and you ignored them and decided to take action on your own without involving the rest of the regional community in a public forum to express their overall opinion and reach a consensus.

I personally do discus not as a privacy and data sharing with those affected by it when I make those decisions in fact you can see Paul's related to such things over the course of time in the Northeast region and in the New York forums and generally consensus throughout the region with input from Mostly non leadership personnel has been in the affirmative and supported those efforts. I highly doubt that every single person in the affected regions of jets to sharing their email for communication purposes. In fact the vast majority of these people have created a dedicated email only to use for Waze which is not used elsewhere specifically so that sharing shouldn't be an issue. Again this is not the place to have that discussion that discussion should be had in a forum with the affected people being able to express their opinions themselves and if the consensus is different leadership can take actions to reflect those decisions on the needs of that region and the community-at-large.

**Comment by vaindil** [comment]
> you were not told it's not "your place to question these decisions"

I think that's _exactly_ what I was told. The wording to me said "you're here to write the bot and help us build Discord, nothing else". I don't know how else to take that message, quite frankly.

> You claim to have never been told any reason why emails were collected, yet I know you were told they were used to grant access to regional resources such as Google Docs, Sheets, etc which are not open to the public at large, and are used as tolls of the editing community.

I should have worded my original comment better. I was never given any _valid_ reason for use of the emails. The spreadsheets that collect the email addresses aren't even limited by email address, so this clearly isn't actually the case. Do the champs feel that high-level discussions are more important than editor privacy, thus those sheets must be protected whereas email addresses are not? This isn't a reason at all because it's not true, hence the argument was discarded.

> yes the post and the Forum and the form itself do not give the link to the server, but the link does exist and is accessible to anyone from the national pinned messages. ... The option to bypass the Forum does exist and just because it isn't mentioned doesn't change that fact that it is possible.

This is quite possibly the dumbest argument I've ever heard. "Links do exist, so you can _technically_ get there, but you have to find them yourself! We won't provide them!" This _exact same argument_ can be used for access to the spreadsheets that collect the email addresses. I **guarantee you** that if I were to go post these public links on the forum, the posts would be removed as soon as they were discovered. So no, the option to bypass the forms IS NOT available.

> leadership is willing to listen if it's brought up in the correct Forum or venue. A problem with a Region's data collection should be addressed in that region with the leadership of that region and with the participation and input of the members of that region which has not happened as far as I know. Not once do I recall the answer being because we said so.

I received a reply from an L6 (R6, whatever you prefer) saying that they didn't care about my stance and it wouldn't be considered. I'm not posting the screenshot here for privacy reasons, but I can assure you that this did in fact happen. Quite literally the definition of "because we said so".

> You conclude by saying that if any reasons were given at all you would consider them however reasons have been given and you ignored them and decided to take action on your own without involving the rest of the regional community in a public forum to express their overall opinion and reach a consensus.

Take a look at the GLR server and you'll see overwhelming support against collection of these email addresses. It was in fact brought up there, and as I mentioned in the paragraph above the leadership said "nope, don't care".

> I highly doubt that every single person in the affected regions [objects] to sharing their email for communication purposes.

But this isn't for communication purposes. The email addresses are being collected as a "just in case". Leadership wants them on file for... why, exactly? Inviting to spreadsheets that are more secret than those containing editor email addresses? I never said that "every single person in the affected regions objects", I said that every single person I've talked to objects. I wouldn't be so naive as to think that literally every person affected agrees with me.

> In fact the vast majority of these people have created a dedicated email only to use for Waze which is not used elsewhere specifically so that sharing shouldn't be an issue.

Is this encouraged anywhere? Do the forms say "you should create an email address just for Waze"? No. This is an unfair burden to require of new editors who wish to join Discord, when sharing it serves _literally no purpose whatsoever_.

> Again this is not the place to have that discussion that discussion should be had in a forum with the affected people being able to express their opinions themselves and if the consensus is different leadership can take actions to reflect those decisions on the needs of that region and the community-at-large.

As non-leadership's opinion is actively ignored as I described above, this seems to be the only way to effect change. Someone has to do something to forcefully get leadership's attention. How else are we to be heard when we're told "nope, don't care"?

**Comment by vaindil** [comment]
GLR is now unrestricted per [this forum post](https://www.waze.com/forum/viewtopic.php?t=238433).

**Comment by nzahn1** [comment]
1.  
> This is a major privacy concern and is unacceptable in any online community.
I don't know how many online communities you've joined in the past decade, but every single one I've experienced has required me to submit, if not validate, an email address or phone number in order to participate. (Just now GitHub is bugging me to validate the email I used to sign up.)
2.
> The reasons given for Waze regions requiring an email address are severely lacking.
Its pretty simple. We secure various communication channels, documents, events, etc by sharing settings or email invites. Also, it helps to have a fall-back when a editor ghosts, and we want to inquire about their roles and responsibilities. 
3. 
> As a result, each region that requires an email address will have its admin commands restricted as long as the email address is a required form field to gain access to the region's Discord server.
Apparently, it's not only admin commands, but also basic lookup functions for the wiki. 
4. 
> my goal is not to punish anyone.
That seems odd. It seems to be your exact goal: to punish a region with limited functionality unless they aquece to your conditions/demands. If it's not a textbook definition of extortion, I don't know what is.

The funny thing about this is: email is not personal information. If you don't want to share the email associated with your social media accounts, bank accounts, work, etc... then a free account is just a web address away.  I wonder if it would have been acceptable to vaindil if: the text requiring an address spelled out how it would be used, and that a Waze-only email account is an excellent decision to segregate communications and maintain privacy?

My biggest issue is the precedent set by the actions of this community member. If an editor becomes disillusioned with the map editing community and decides to "undo" the work they contributed on the map, the response from the volunteer community and Waze would be swift and severe.  The fact that the the editor in this case contributes to the Waze community through his extensive knowledge, skill, and experience editing code rather than editing the map should not give him veto power over the decisions of the established community leadership structure.  I don't see the leaders from the MAR region capitulating on this issue now that something is being held over their heads.

**Comment by vaindil** [comment]
> I don't know how many online communities you've joined in the past decade, but every single one I've experienced has required me to submit, if not validate, an email address or phone number in order to participate. (Just now GitHub is bugging me to validate the email I used to sign up.)

You misread what I meant by "community". Waze requires an email address because you need to make an account. Discord and GitHub require them for that same reason. All three are international corporations that I fully trust to keep my email address private. You are a group of volunteer editors, and you are under no obligation whatsoever to keep my email address private. See the difference?

> Its pretty simple. We secure various communication channels, documents, events, etc by sharing settings or email invites.

And just how often are those shared by email address and not by link? I'm sure the answer will be a very small number.

> Also, it helps to have a fall-back when a editor ghosts, and we want to inquire about their roles and responsibilities.

The problem is that it's none of your business when an editor ghosts. They're volunteers. If they leave, you have no right whatsoever to email them asking where they went. None. This is the heart of the issue here.

> Apparently, it's not only admin commands, but also basic lookup functions for the wiki.

Yes, I made that change but forgot to update the issue. Will do after I submit this comment.

> That seems odd. It seems to be your exact goal: to punish a region with limited functionality unless they aquece to your conditions/demands. If it's not a textbook definition of extortion, I don't know what is.

You're under no obligation to use my bot, just as I'm under no obligation to provide it.

> The funny thing about this is: email is not personal information.

And this is where you're completely, unequivocally wrong. Just as one example, the US Department of Labor [disagrees with you](https://www.dol.gov/general/ppii). I invite you to find a single reputable source to support your position.

> My biggest issue is the precedent set by the actions of this community member. If an editor becomes disillusioned with the map editing community and decides to "undo" the work they contributed on the map, the response from the volunteer community and Waze would be swift and severe.

Waze's response would be swift and severe because you're violating their terms of service and damaging their brand.

> I don't see the leaders from the MAR region capitulating on this issue now that something is being held over their heads.

Feel free to run your own bot if you feel that way, because I'm not backing down. The bot is something I work on in my free time and host on my server because I love the editing community and want to help it grow. I can only do so much, however, when the leadership is incompetent.

**Comment by rzaccari** [comment]
> Waze requires an email address because you need to make an account.

I have plenty of accounts that have zero connection to my email address, so this is a justification.

> The problem is that it's none of your business when an editor ghosts. They're volunteers. If they leave, you have no right whatsoever to email them asking where they went. None. This is the heart of the issue here.

I know it will surprise you, but again I disagree.  We are in a downswing of editors and I personally have emailed editors that are MIA for several reasons.  First, I definitely care if we did something that irritated or pissed them off and they left for that reason.  I may not be able to change the reasons but I certainly will try. Second, there are policies that apply to ghosting editors.  I never want to see an editor loser their AM or other access/etc without them knowing it will happen.

> Feel free to run your own bot if you feel that way, because I'm not backing down. The bot is something I work on in my free time and host on my server because I love the editing community and want to help it grow. I can only do so much, however, when the leadership is incompetent.

Really?  Incompetent because you do not agree with their approaches to things?  In a world where anyone can go to GMail or a dozen other free email services and create a throwaway email address, is it really worth all of this?  Are you disabling your bot from the MapRaid/Global Discord server?  I had to submit my email address there to mentor in the Philly MapRaid and everyone before that.  

There are several things that really interest me about this whole thing. 

- We have been asking for a form submission in MD for a very long time, in every communication with new users; in fact, we have always told people to use a separate account if they are uncomfortable sharing the acct they used to register Waze and/or receive their daily email on
- I am unaware of any situation where any editor was told to supply it if they provided none@nobody.net nor any actions taken if an email bounced/proved invalid
- I too am of the opinion that today the bot is being held hostage because of email addresses; what will it be tomorrow?  The RC is unacceptable, an SM was mean?  At the end of the day, even using Discord (or GHO) to interact with other MAR editors is not required to edit either, just as the bot is not required.

Finally, I will close by thanking you for the service you provided everyone up to this point.  I sure wish you would have discussed it further.  I know the whole MAR leadership and I cannot fathom any one of them saying "you're here to write the bot and help us build Discord, nothing else."  Since you are unable to adjust your position, I wish you well.

**Comment by Mikecom32** [comment]
I'm a relatively casual editor, but saw a link to this issue and feel that I need to weigh in.

>I know it will surprise you, but again I disagree. We are in a downswing of editors and I personally have emailed editors that are MIA for several reasons.

I think it's a bit inappropriate to bug someone into coming back to an online volunteer position when you don't know their reasons for leaving. If someone ghosted, there's probably a real life reason for it. 

>In a world where anyone can go to GMail or a dozen other free email services and create a throwaway email address, is it really worth all of this? 

This directly contradicts your previous statement. If someone created a throwaway address, you're not going to be able to contact them about coming back. If you really wanted it for a secondary (or really, tertiary, as the Waze platform/forums should be secondary) contact method, you'd require it was valid.

If a user wants to volunteer their email address as a contact method, it should be up to them to do so. There are no privacy policies, no assurance of secure storage, no details on who has access to the email list and for what reasons someone would be granted access. Requiring the user to supply their personal email address to such a database seems unnecessary. If you need another contact method, messaging them on the Waze forums should suffice. If someone chooses to leave the community, they shouldn't need to worry about being harassed via other contact methods, and shouldn't need to worry about their Waze username possibly being linked to a personal email address should that database be leaked or accessed inappropriately.

>I am unaware of any situation where any editor was told to supply it if they provided none@nobody.net nor any actions taken if an email bounced/proved invalid

If this is really the case, **clearly mark the field as optional** and move on. That should satisfy both sides and we can all move on.

>I too am of the opinion that today the bot is being held hostage because of email addresses; what will it be tomorrow? The RC is unacceptable, an SM was mean?

[Classic slippery slope fallacy](https://en.wikipedia.org/wiki/Slippery_slope#Defining_features_of_slippery_slope_arguments). RCs and SMs don't have direct privacy concerns. This isn't a fair argument. If we want to go down this road, @vaindil could just as easily say "today they're asking for email addresses; what will it be tomorrow? Cell phone numbers? Home addresses?". There's no valid point here, and we shouldn't go down this road. It is entirely unproductive.

**Comment by Mikecom32** [comment]
>If you're going to lose your AM you don't want to know? 

I don't think that will provide for anything useful. If having AM status was important, you'd probably still be around to contribute. PM them on the Waze forums. I'm sure most members have email notifications turned on for PMs.

Most users do not have throwaway emails, and having multiple addresses or aliases forwarding to a primary address for privacy is well beyond the technical prowess of the average user.

**Comment by rzaccari** [comment]
I like to think of myself as a person, not set in my ways.  On my drive this morning, I realized that I have digressed.  My opinions just do not matter.  I have the reasons I think it's reasonable but I myself am not the sole person to decide policy for MAR.  My reason for even jumping into the discussion from the beginning was to disagree with the idea that a single person feels it appropriate to decide for a group.  The reasons of a single person (me, you or anyone other single person) are really irrelevant in this situation.  All of our reasons are also irrelevant.  While we have a fairly well-defined hierarchical setup, MAR tends to be democratic and it is distasteful to have something jammed down the throat(s) of everyone due to a single, non-flexible decision.

I will say that I have no idea who said it was none of your business.  MAR's form is MAR's creation and it is used and adapted in a somewhat democratic process.  A single person generally does not speak for the whole.  I feel fairly certain that had this been handled a different way, a discussion would have taken place and a totally different outcome would have occurred.  Just to relate a part of a discussion had earlier today, it did not occur to me that, to my knowledge we have never used an email address for a non-AM or above.  My opinion on the whole email discussion has changed.  

My last statement(s) yesterday still stands though.  I thank you for your service to to this point.  I also wish you well.

**Comment by vaindil** [comment]
Looks like the MAR form no longer requires an email address, so MAR is no longer restricted. I'll close this issue out as the original problem has been resolved. Note that the code does remain in the bot to reactivate in the future should emails be required at some point by any region.
